---
dist: xenial
language: ruby
python: '2.7'
rvm:
- 2.5.7
- 2.6.5
cache:
  bundler: true
  yarn: true
  timeout: 600
addons:
  chrome: beta
  postgresql: '12'
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  matrix:
  - TEST_SUITE=spec
  - TEST_SUITE=spec:routes
  - TEST_SUITE=spec:javascript
  - TEST_SUITE=spec:compile
  - TEST_SUITE=spec:jest
  - TEST_SUITE=spec:debride
matrix:
  exclude:
  - rvm: 2.5.7
    env: TEST_SUITE=spec:routes
  - rvm: 2.5.7
    env: TEST_SUITE=spec:javascript
  - rvm: 2.5.7
    env: TEST_SUITE=spec:compile
  - rvm: 2.5.7
    env: TEST_SUITE=spec:jest
  - rvm: 2.5.7
    env: TEST_SUITE=spec:debride
bundler_args: "--no-deployment"
before_install:
  - source tools/ci/before_install.sh
# setting up postgres 12 is quite a pain, see:
# https://travis-ci.community/t/test-against-postgres-12/6768/8
  - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo pg_ctlcluster 12 main restart
install: bin/setup
before_script: source tools/ci/before_script.sh
script: bundle exec rake $TEST_SUITE
after_script: source tools/ci/after_script.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9a9f972a1225d28e0f05
    on_success: change
    on_failure: always
    on_start: never
